# Generated by Django 3.0.3 on 2020-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200208_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(default=None),
        ),
    ]
